/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#0E6E83',
        'primary-strong': '#0A5365',
        'primary-soft': '#ECF4F6',
        'primary-line': '#CFE3E8',
        navy: '#06303C',
        ink: '#13202A',
        'ink-2': '#33454F',
        muted: '#647781',
        faint: '#93A3AC',
        line: '#E6EBEE',
        'line-soft': '#F0F3F5',
        background: '#F5F7F8',
        surface: '#FFFFFF',
        success: '#15875B',
        'success-bg': '#E8F4EE',
        'success-dot': '#23A06B',
        warning: '#B26C1E',
        'warning-bg': '#FAF0E2',
        'warning-dot': '#D08A33',
        off: '#697982',
        'off-bg': '#EEF1F3',
        'off-dot': '#9AA8B0',
        danger: '#C5453F',
        'danger-bg': '#FBECEB',
      },
      fontFamily: {
        sans: [
          'Pretendard Variable',
          'Pretendard',
          '-apple-system',
          'BlinkMacSystemFont',
          'system-ui',
          'Apple SD Gothic Neo',
          'Malgun Gothic',
          'sans-serif',
        ],
      },
      fontSize: {
        h1: ['27px', { lineHeight: '1.2', letterSpacing: '-0.8px', fontWeight: '800' }],
        section: ['15.5px', { lineHeight: '1.35', letterSpacing: '-0.2px', fontWeight: '700' }],
        body: ['15px', { lineHeight: '1.5', fontWeight: '500' }],
        label: ['13px', { lineHeight: '1.4', fontWeight: '600' }],
        table: ['12.5px', { lineHeight: '1.4', fontWeight: '600' }],
        badge: ['12px', { lineHeight: '1.2', letterSpacing: '0.2px', fontWeight: '700' }],
        kpi: ['32px', { lineHeight: '1.05', letterSpacing: '-1px', fontWeight: '800' }],
      },
      borderRadius: {
        card: '12px',
        control: '8px',
        badge: '7px',
      },
      boxShadow: {
        card: '0 1px 2px rgba(19, 32, 42, 0.03)',
        modal: '0 24px 70px rgba(9, 20, 26, 0.35)',
        drawer: '-20px 0 60px rgba(9, 20, 26, 0.25)',
        popover: '0 12px 36px rgba(9, 20, 26, 0.16)',
        login: '0 4px 24px rgba(19, 32, 42, 0.05)',
      },
    },
  },
  plugins: [],
}
