import type { SalesOrder, SalesOrderLine, SoItemUnit } from './so-ui-model'

/** 본사 출고 창고 옵션 — GET /inventory/warehouses/hq 응답에 해당 */
export const SO_HQ_WAREHOUSE_OPTIONS = [{ code: 'WH-HQ-001', name: '본사 중앙창고' }] as const

/** SO-02/03/06 데모용 공통 6라인 (요청 → 승인 → 출고 단계별 수량) */
function richLines(stage: 'REQUESTED' | 'APPROVED' | 'DELIVERED'): SalesOrderLine[] {
  const base = [
    { availableStock: 420, itemName: '엔진오일 필터 (2.0L gasoline)', requested: 80, approved: 80, shipped: 80, delivered: 80, sku: 'HMC-EN-00214', unit: 'EA' as const },
    { availableStock: 78, itemName: '브레이크 패드 세트 (전륜)', requested: 40, approved: 40, shipped: 40, delivered: 38, sku: 'HMC-BR-01102', unit: 'SET' as const },
    { availableStock: 142, itemName: '에어 클리너 카트리지', requested: 60, approved: 60, shipped: 60, delivered: 60, sku: 'HMC-EN-10331', unit: 'EA' as const },
    { availableStock: 48, itemName: '스파크 플러그 (이리듐)', requested: 120, approved: 48, shipped: 48, delivered: 48, sku: 'HMC-SP-00673', unit: 'EA' as const },
    { availableStock: 8, itemName: '와이퍼 블레이드 24"', requested: 10, approved: 10, shipped: 12, delivered: 10, sku: 'HMC-AC-40229', unit: 'EA' as const },
    { availableStock: 240, itemName: '엔진 쿨런트 1L', requested: 10, approved: 10, shipped: 10, delivered: 10, sku: 'HMC-CL-50710', unit: 'L' as const },
  ]

  return base.map((line, index) => ({
    approvedQuantity: stage === 'REQUESTED' ? null : line.approved,
    availableStock: line.availableStock,
    deliveredQuantity: stage === 'DELIVERED' ? line.delivered : null,
    itemName: line.itemName,
    lineNo: index + 1,
    priority: line.sku === 'HMC-SP-00673' ? 'URGENT' : 'NORMAL',
    requestedQuantity: line.requested,
    shippedQuantity: stage === 'APPROVED' || stage === 'DELIVERED' ? line.shipped : null,
    sku: line.sku,
    unit: line.unit,
  }))
}

function simpleLines(
  entries: Array<{ name: string; quantity: number; sku: string; stock: number; unit: SoItemUnit }>,
  filled: boolean,
): SalesOrderLine[] {
  return entries.map((entry, index) => ({
    approvedQuantity: filled ? entry.quantity : null,
    availableStock: entry.stock,
    deliveredQuantity: null,
    itemName: entry.name,
    lineNo: index + 1,
    priority: 'NORMAL',
    requestedQuantity: entry.quantity,
    shippedQuantity: null,
    sku: entry.sku,
    unit: entry.unit,
  }))
}

/** 백엔드 연동 전 화면 확인용 하드코딩 발주 요청 데이터 */
export const SALES_ORDER_FIXTURES: SalesOrder[] = [
  {
    approvedAt: null,
    approverName: null,
    branchCode: 'BR-04',
    branchName: '강남 1지점',
    branchRegion: '서울 강남구',
    desiredAt: '2026-06-14',
    events: [
      { actorName: '정유진', actorOrg: '강남 1지점', description: '발주 요청 제출 · 6개 라인 320 EA', id: 1, occurredAt: '2026-06-11T09:42:00', type: 'REQUESTED' },
      { actorName: '정유진', actorOrg: '강남 1지점', description: '와이퍼 블레이드 수량 6 → 10 수정', id: 2, occurredAt: '2026-06-11T09:38:00', type: 'EDITED' },
      { actorName: '정유진', actorOrg: '강남 1지점', description: '신규 요청서 작성 시작', id: 3, occurredAt: '2026-06-11T09:24:00', type: 'DRAFT' },
    ],
    id: 1,
    invoiceNo: null,
    lines: richLines('REQUESTED'),
    note: '정기 점검 시즌 대비 보충 요청. 스파크 플러그는 차종 G70용 우선 출고 부탁드립니다.',
    receiveWarehouseCode: 'WH-04A',
    receiveWarehouseName: '강남 1지점 · 부품창고',
    rejectReason: null,
    reqNo: 'REQ-2026-0512',
    requestedAt: '2026-06-11T09:42:00',
    requesterName: '정유진',
    requesterRole: '서비스 매니저',
    shipWarehouseCode: null,
    shipWarehouseName: null,
    shippedAt: null,
    status: 'REQUESTED',
    transport: null,
  },
  {
    approvedAt: null,
    approverName: null,
    branchCode: 'BR-11',
    branchName: '부산 해운대지점',
    branchRegion: '부산 해운대구',
    desiredAt: '2026-06-15',
    events: [
      { actorName: '이재훈', actorOrg: '부산 해운대지점', description: '발주 요청 제출 · 3개 라인 94 EA', id: 1, occurredAt: '2026-06-11T08:15:00', type: 'REQUESTED' },
    ],
    id: 2,
    invoiceNo: null,
    lines: simpleLines(
      [
        { name: '배터리 12V 80Ah', quantity: 40, sku: 'HMC-EL-04481', stock: 0, unit: 'EA' },
        { name: '와이퍼 블레이드 24"', quantity: 30, sku: 'HMC-AC-40229', stock: 75, unit: 'EA' },
        { name: '에어 클리너 카트리지', quantity: 24, sku: 'HMC-EN-10331', stock: 142, unit: 'EA' },
      ],
      false,
    ),
    note: null,
    receiveWarehouseCode: 'WH-11A',
    receiveWarehouseName: '부산 해운대지점 · 부품창고',
    rejectReason: null,
    reqNo: 'REQ-2026-0511',
    requestedAt: '2026-06-11T08:15:00',
    requesterName: '이재훈',
    requesterRole: '지점 담당자',
    shipWarehouseCode: null,
    shipWarehouseName: null,
    shippedAt: null,
    status: 'REQUESTED',
    transport: null,
  },
  {
    approvedAt: '2026-06-11T11:18:00',
    approverName: '박지훈',
    branchCode: 'BR-04',
    branchName: '강남 1지점',
    branchRegion: '서울 강남구',
    desiredAt: '2026-06-13',
    events: [
      { actorName: '박지훈', actorOrg: '본사 물류팀', description: '승인 · 출고 창고 본사 중앙창고 지정', id: 1, occurredAt: '2026-06-11T11:18:00', type: 'APPROVED' },
      { actorName: '정유진', actorOrg: '강남 1지점', description: '발주 요청 제출 · 6개 라인 320 EA', id: 2, occurredAt: '2026-06-10T16:40:00', type: 'REQUESTED' },
    ],
    id: 3,
    invoiceNo: null,
    lines: richLines('APPROVED'),
    note: null,
    receiveWarehouseCode: 'WH-04A',
    receiveWarehouseName: '강남 1지점 · 부품창고',
    rejectReason: null,
    reqNo: 'REQ-2026-0510',
    requestedAt: '2026-06-10T16:40:00',
    requesterName: '정유진',
    requesterRole: '서비스 매니저',
    shipWarehouseCode: 'WH-HQ-001',
    shipWarehouseName: '본사 중앙창고',
    shippedAt: null,
    status: 'APPROVED',
    transport: null,
  },
  {
    approvedAt: '2026-06-10T10:02:00',
    approverName: '박지훈',
    branchCode: 'BR-21',
    branchName: '대전 유성지점',
    branchRegion: '대전 유성구',
    desiredAt: '2026-06-10',
    events: [
      { actorName: '박지훈', actorOrg: '본사 물류팀', description: '승인 · 출고 대기 전환', id: 1, occurredAt: '2026-06-10T10:02:00', type: 'APPROVED' },
      { actorName: '김도윤', actorOrg: '대전 유성지점', description: '발주 요청 제출 · 4개 라인 240 EA', id: 2, occurredAt: '2026-06-09T17:21:00', type: 'REQUESTED' },
    ],
    id: 4,
    invoiceNo: null,
    lines: simpleLines(
      [
        { name: '스파크 플러그 (이리듐)', quantity: 160, sku: 'HMC-SP-00673', stock: 960, unit: 'EA' },
        { name: '엔진오일 필터 (2.0L gasoline)', quantity: 60, sku: 'HMC-EN-00214', stock: 420, unit: 'EA' },
        { name: '엔진 쿨런트 1L', quantity: 20, sku: 'HMC-CL-50710', stock: 240, unit: 'L' },
      ],
      true,
    ),
    note: null,
    receiveWarehouseCode: 'WH-21A',
    receiveWarehouseName: '대전 유성지점 · 부품창고',
    rejectReason: null,
    reqNo: 'REQ-2026-0509',
    requestedAt: '2026-06-09T17:21:00',
    requesterName: '김도윤',
    requesterRole: '지점 담당자',
    shipWarehouseCode: 'WH-HQ-001',
    shipWarehouseName: '본사 중앙창고',
    shippedAt: null,
    status: 'APPROVED',
    transport: null,
  },
  {
    approvedAt: '2026-06-09T14:30:00',
    approverName: '오세훈',
    branchCode: 'BR-04',
    branchName: '강남 1지점',
    branchRegion: '서울 강남구',
    desiredAt: '2026-06-12',
    events: [
      { actorName: '김정수', actorOrg: '본사 중앙창고', description: '출고 확정 · 송장 HMC-44219-026 · 6개 라인 250 EA', id: 1, occurredAt: '2026-06-10T14:18:00', type: 'APPROVED' },
      { actorName: '오세훈', actorOrg: '본사 물류팀', description: '승인 · 출고 창고 본사 중앙창고 지정', id: 2, occurredAt: '2026-06-09T14:30:00', type: 'APPROVED' },
      { actorName: '정유진', actorOrg: '강남 1지점', description: '발주 요청 제출 · 6개 라인 320 EA', id: 3, occurredAt: '2026-06-09T09:12:00', type: 'REQUESTED' },
    ],
    id: 5,
    invoiceNo: 'HMC-44219-026',
    lines: richLines('APPROVED'),
    note: null,
    receiveWarehouseCode: 'WH-04A',
    receiveWarehouseName: '강남 1지점 · 부품창고',
    rejectReason: null,
    reqNo: 'REQ-2026-0498',
    requestedAt: '2026-06-09T09:12:00',
    requesterName: '정유진',
    requesterRole: '서비스 매니저',
    shipWarehouseCode: 'WH-HQ-001',
    shipWarehouseName: '본사 중앙창고',
    shippedAt: '2026-06-10T14:18:00',
    status: 'APPROVED',
    transport: '자사 차량 (대형 1톤) · 02머4421',
  },
  {
    approvedAt: '2026-06-08T11:00:00',
    approverName: '박지훈',
    branchCode: 'BR-17',
    branchName: '광주 서구지점',
    branchRegion: '광주 서구',
    desiredAt: '2026-06-09',
    events: [
      { actorName: '박지훈', actorOrg: '본사 물류팀', description: '승인 · 출고 대기 전환', id: 1, occurredAt: '2026-06-08T11:00:00', type: 'APPROVED' },
      { actorName: '최은서', actorOrg: '광주 서구지점', description: '발주 요청 제출 · 2개 라인 64 EA', id: 2, occurredAt: '2026-06-08T09:30:00', type: 'REQUESTED' },
    ],
    id: 6,
    invoiceNo: null,
    lines: simpleLines(
      [
        { name: '헤드램프 어셈블리 LH', quantity: 24, sku: 'HMC-LT-00088', stock: 30, unit: 'EA' },
        { name: '와이퍼 블레이드 24"', quantity: 40, sku: 'HMC-AC-40229', stock: 75, unit: 'EA' },
      ],
      true,
    ),
    note: null,
    receiveWarehouseCode: 'WH-17A',
    receiveWarehouseName: '광주 서구지점 · 부품창고',
    rejectReason: null,
    reqNo: 'REQ-2026-0508',
    requestedAt: '2026-06-08T09:30:00',
    requesterName: '최은서',
    requesterRole: '지점 관리자',
    shipWarehouseCode: 'WH-HQ-001',
    shipWarehouseName: '본사 중앙창고',
    shippedAt: null,
    status: 'APPROVED',
    transport: null,
  },
  {
    approvedAt: null,
    approverName: null,
    branchCode: 'BR-09',
    branchName: '수원 영통지점',
    branchRegion: '경기 수원시',
    desiredAt: '2026-06-11',
    events: [
      { actorName: '박지훈', actorOrg: '본사 물류팀', description: '거절 · 사유: 중복 요청', id: 1, occurredAt: '2026-06-08T13:45:00', type: 'REJECTED' },
      { actorName: '한지민', actorOrg: '수원 영통지점', description: '발주 요청 제출 · 1개 라인 12 EA', id: 2, occurredAt: '2026-06-08T10:05:00', type: 'REQUESTED' },
    ],
    id: 7,
    invoiceNo: null,
    lines: simpleLines(
      [{ name: '엔진 쿨런트 4L', quantity: 12, sku: 'HMC-CL-50714', stock: 88, unit: 'L' }],
      false,
    ),
    note: null,
    receiveWarehouseCode: 'WH-09A',
    receiveWarehouseName: '수원 영통지점 · 부품창고',
    rejectReason: '중복 요청',
    reqNo: 'REQ-2026-0507',
    requestedAt: '2026-06-08T10:05:00',
    requesterName: '한지민',
    requesterRole: '지점 담당자',
    shipWarehouseCode: null,
    shipWarehouseName: null,
    shippedAt: null,
    status: 'REJECTED',
    transport: null,
  },
  {
    approvedAt: '2026-06-05T15:20:00',
    approverName: '오세훈',
    branchCode: 'BR-04',
    branchName: '강남 1지점',
    branchRegion: '서울 강남구',
    desiredAt: '2026-06-08',
    events: [
      { actorName: '정유진', actorOrg: '강남 1지점', description: '도착 확정 · 1,180 EA 입고 반영', id: 1, occurredAt: '2026-06-08T10:30:00', type: 'DELIVERED' },
      { actorName: '김정수', actorOrg: '본사 중앙창고', description: '출고 확정 · 송장 HMC-44102-871', id: 2, occurredAt: '2026-06-06T13:00:00', type: 'APPROVED' },
      { actorName: '오세훈', actorOrg: '본사 물류팀', description: '승인', id: 3, occurredAt: '2026-06-05T15:20:00', type: 'APPROVED' },
      { actorName: '정유진', actorOrg: '강남 1지점', description: '발주 요청 제출', id: 4, occurredAt: '2026-06-05T09:00:00', type: 'REQUESTED' },
    ],
    id: 8,
    invoiceNo: 'HMC-44102-871',
    lines: simpleLines(
      [
        { name: '스파크 플러그 (이리듐)', quantity: 1000, sku: 'HMC-SP-00673', stock: 960, unit: 'EA' },
        { name: '엔진오일 필터 (2.0L gasoline)', quantity: 180, sku: 'HMC-EN-00214', stock: 420, unit: 'EA' },
      ],
      true,
    ),
    note: null,
    receiveWarehouseCode: 'WH-04A',
    receiveWarehouseName: '강남 1지점 · 부품창고',
    rejectReason: null,
    reqNo: 'REQ-2026-0506',
    requestedAt: '2026-06-05T09:00:00',
    requesterName: '정유진',
    requesterRole: '서비스 매니저',
    shipWarehouseCode: 'WH-HQ-001',
    shipWarehouseName: '본사 중앙창고',
    shippedAt: '2026-06-06T13:00:00',
    status: 'DELIVERED',
    transport: '용차',
  },
  {
    approvedAt: '2026-06-04T10:10:00',
    approverName: '박지훈',
    branchCode: 'BR-14',
    branchName: '대구 수성지점',
    branchRegion: '대구 수성구',
    desiredAt: '2026-06-12',
    events: [
      { actorName: '강주원', actorOrg: '본사 중앙창고', description: '출고 확정 · 3개 라인 76 EA', id: 1, occurredAt: '2026-06-05T11:40:00', type: 'APPROVED' },
      { actorName: '박지훈', actorOrg: '본사 물류팀', description: '승인', id: 2, occurredAt: '2026-06-04T10:10:00', type: 'APPROVED' },
      { actorName: '윤성준', actorOrg: '대구 수성지점', description: '발주 요청 제출', id: 3, occurredAt: '2026-06-04T08:55:00', type: 'REQUESTED' },
    ],
    id: 9,
    invoiceNo: 'HMC-44180-440',
    lines: simpleLines(
      [
        { name: '에어 클리너 카트리지', quantity: 48, sku: 'HMC-EN-10331', stock: 142, unit: 'EA' },
        { name: '엔진 쿨런트 1L', quantity: 28, sku: 'HMC-CL-50710', stock: 240, unit: 'L' },
      ],
      true,
    ),
    note: null,
    receiveWarehouseCode: 'WH-14A',
    receiveWarehouseName: '대구 수성지점 · 부품창고',
    rejectReason: null,
    reqNo: 'REQ-2026-0505',
    requestedAt: '2026-06-04T08:55:00',
    requesterName: '윤성준',
    requesterRole: '지점 담당자',
    shipWarehouseCode: 'WH-HQ-001',
    shipWarehouseName: '본사 중앙창고',
    shippedAt: '2026-06-05T11:40:00',
    status: 'APPROVED',
    transport: '택배',
  },
  {
    approvedAt: null,
    approverName: null,
    branchCode: 'BR-31',
    branchName: '제주 노형지점',
    branchRegion: '제주 제주시',
    desiredAt: '2026-06-10',
    events: [
      { actorName: '서지우', actorOrg: '제주 노형지점', description: '요청 취소', id: 1, occurredAt: '2026-06-04T15:00:00', type: 'CANCELED' },
      { actorName: '서지우', actorOrg: '제주 노형지점', description: '발주 요청 제출', id: 2, occurredAt: '2026-06-03T13:30:00', type: 'REQUESTED' },
    ],
    id: 10,
    invoiceNo: null,
    lines: simpleLines(
      [
        { name: '와이퍼 블레이드 24"', quantity: 24, sku: 'HMC-AC-40229', stock: 75, unit: 'EA' },
      ],
      false,
    ),
    note: null,
    receiveWarehouseCode: 'WH-31A',
    receiveWarehouseName: '제주 노형지점 · 부품창고',
    rejectReason: null,
    reqNo: 'REQ-2026-0504',
    requestedAt: '2026-06-03T13:30:00',
    requesterName: '서지우',
    requesterRole: '지점 담당자',
    shipWarehouseCode: null,
    shipWarehouseName: null,
    shippedAt: null,
    status: 'CANCELED',
    transport: null,
  },
  {
    approvedAt: '2026-06-02T10:40:00',
    approverName: '오세훈',
    branchCode: 'BR-04',
    branchName: '강남 1지점',
    branchRegion: '서울 강남구',
    desiredAt: '2026-06-05',
    events: [
      { actorName: '정유진', actorOrg: '강남 1지점', description: '도착 확정 · 88 EA 입고 반영', id: 1, occurredAt: '2026-06-05T09:50:00', type: 'DELIVERED' },
      { actorName: '김정수', actorOrg: '본사 중앙창고', description: '출고 확정', id: 2, occurredAt: '2026-06-03T14:25:00', type: 'APPROVED' },
      { actorName: '오세훈', actorOrg: '본사 물류팀', description: '승인', id: 3, occurredAt: '2026-06-02T10:40:00', type: 'APPROVED' },
      { actorName: '정유진', actorOrg: '강남 1지점', description: '발주 요청 제출', id: 4, occurredAt: '2026-06-02T09:10:00', type: 'REQUESTED' },
    ],
    id: 11,
    invoiceNo: 'HMC-44095-103',
    lines: simpleLines(
      [
        { name: '엔진 쿨런트 1L', quantity: 60, sku: 'HMC-CL-50710', stock: 240, unit: 'L' },
        { name: '쿨런트 보조탱크 캡', quantity: 28, sku: 'HMC-CL-50822', stock: 64, unit: 'EA' },
      ],
      true,
    ),
    note: null,
    receiveWarehouseCode: 'WH-04A',
    receiveWarehouseName: '강남 1지점 · 부품창고',
    rejectReason: null,
    reqNo: 'REQ-2026-0448',
    requestedAt: '2026-06-02T09:10:00',
    requesterName: '정유진',
    requesterRole: '서비스 매니저',
    shipWarehouseCode: 'WH-HQ-001',
    shipWarehouseName: '본사 중앙창고',
    shippedAt: '2026-06-03T14:25:00',
    status: 'DELIVERED',
    transport: '자사 차량 (소형)',
  },
  {
    approvedAt: null,
    approverName: null,
    branchCode: 'BR-04',
    branchName: '강남 1지점',
    branchRegion: '서울 강남구',
    desiredAt: '2026-06-03',
    events: [
      { actorName: '박지훈', actorOrg: '본사 물류팀', description: '거절 · 사유: 요청 수량 과다', id: 1, occurredAt: '2026-06-01T11:30:00', type: 'REJECTED' },
      { actorName: '정유진', actorOrg: '강남 1지점', description: '발주 요청 제출', id: 2, occurredAt: '2026-06-01T09:20:00', type: 'REQUESTED' },
    ],
    id: 12,
    invoiceNo: null,
    lines: simpleLines(
      [{ name: '배터리 12V 80Ah', quantity: 12, sku: 'HMC-EL-04481', stock: 0, unit: 'EA' }],
      false,
    ),
    note: null,
    receiveWarehouseCode: 'WH-04A',
    receiveWarehouseName: '강남 1지점 · 부품창고',
    rejectReason: '요청 수량 과다',
    reqNo: 'REQ-2026-0459',
    requestedAt: '2026-06-01T09:20:00',
    requesterName: '정유진',
    requesterRole: '서비스 매니저',
    shipWarehouseCode: null,
    shipWarehouseName: null,
    shippedAt: null,
    status: 'REJECTED',
    transport: null,
  },
]
