import type { User, UserActivity } from './types'

/** 소속(창고) 선택 옵션 — User 서비스 목록 API 연동 전 임시 필터 목록 */
export const BELONG_OPTIONS = [
  '본사 중앙창고',
  '서울 1창고',
  '서울 2창고',
  '부산 1창고',
  '부산 2창고',
  '인천 1창고',
  '대구 1창고',
  '광주 1창고',
  '대전 1창고',
] as const

/** 백엔드 연동 전 화면 확인용 하드코딩 사용자 데이터 */
export const USER_FIXTURES: User[] = [
  {
    email: 'jskim@hyundaiparts.com',
    empNo: 'HMC0001',
    id: 1,
    joinedAt: '2023-04-12',
    name: '김정수',
    rank: '과장',
    role: 'BRANCH_MANAGER',
    status: 'ACTIVE',
    warehouseName: '서울 1창고',
  },
  {
    email: 'mhlee@hyundaiparts.com',
    empNo: 'HMC0002',
    id: 2,
    joinedAt: '2021-11-02',
    name: '이민호',
    rank: '차장',
    role: 'HQ_MANAGER',
    status: 'ACTIVE',
    warehouseName: '본사 중앙창고',
  },
  {
    email: 'sypark@hyundaiparts.com',
    empNo: 'HMC0003',
    id: 3,
    joinedAt: '2026-05-18',
    name: '박서연',
    rank: '사원',
    role: 'BRANCH_STAFF',
    status: 'PENDING',
    warehouseName: '부산 2창고',
  },
  {
    email: 'dychoi@hyundaiparts.com',
    empNo: 'HMC0004',
    id: 4,
    joinedAt: '2024-02-09',
    name: '최도윤',
    rank: '대리',
    role: 'BRANCH_MANAGER',
    status: 'ACTIVE',
    warehouseName: '인천 1창고',
  },
  {
    email: 'hjeong@hyundaiparts.com',
    empNo: 'HMC0005',
    id: 5,
    joinedAt: '2025-08-22',
    name: '정하늘',
    rank: '주임',
    role: 'HQ_STAFF',
    status: 'ACTIVE',
    warehouseName: '본사 중앙창고',
  },
  {
    email: 'jwhan@hyundaiparts.com',
    empNo: 'HMC0006',
    id: 6,
    joinedAt: '2024-06-30',
    name: '한지우',
    rank: '사원',
    role: 'BRANCH_STAFF',
    status: 'SUSPENDED',
    warehouseName: '대구 1창고',
  },
  {
    email: 'shoh@hyundaiparts.com',
    empNo: 'HMC0007',
    id: 7,
    joinedAt: '2022-03-14',
    name: '오세훈',
    rank: '부장',
    role: 'ADMIN',
    status: 'ACTIVE',
    warehouseName: '본사 중앙창고',
  },
  {
    email: 'gryoon@hyundaiparts.com',
    empNo: 'HMC0008',
    id: 8,
    joinedAt: '2025-01-19',
    name: '윤가람',
    rank: '주임',
    role: 'BRANCH_STAFF',
    status: 'ACTIVE',
    warehouseName: '광주 1창고',
  },
  {
    email: 'ywseo@hyundaiparts.com',
    empNo: 'HMC0009',
    id: 9,
    joinedAt: '2026-05-20',
    name: '서연우',
    rank: '과장',
    role: 'BRANCH_MANAGER',
    status: 'PENDING',
    warehouseName: '대전 1창고',
  },
  {
    email: 'jwkang@hyundaiparts.com',
    empNo: 'HMC0010',
    id: 10,
    joinedAt: '2023-09-05',
    name: '강주원',
    rank: '대리',
    role: 'HQ_STAFF',
    status: 'ACTIVE',
    warehouseName: '본사 중앙창고',
  },
]

/** 마이페이지 최근 활동 (최근 5건) */
export const MY_ACTIVITY_FIXTURES: UserActivity[] = [
  {
    delta: null,
    description: '서울 1창고 · Chrome / Windows',
    id: 1,
    occurredAt: '2026-06-11T08:52:10',
    refCode: null,
    type: 'LOGIN',
  },
  {
    delta: -3,
    description: '엔진오일 필터',
    id: 2,
    occurredAt: '2026-06-10T17:48:30',
    refCode: 'HMC-EN-00214',
    type: 'ADJUST',
  },
  {
    delta: null,
    description: '재고 부족 리포트 (6월 2주차)',
    id: 3,
    occurredAt: '2026-06-10T11:03:44',
    refCode: null,
    type: 'VIEW',
  },
  {
    delta: 40,
    description: '엔진오일 필터',
    id: 4,
    occurredAt: '2026-06-09T09:08:11',
    refCode: 'HMC-EN-00214',
    type: 'ADJUST',
  },
  {
    delta: null,
    description: '서울 1창고 · Chrome / Windows',
    id: 5,
    occurredAt: '2026-06-09T09:05:02',
    refCode: null,
    type: 'LOGIN',
  },
]

/** 마지막 비밀번호 변경일 (마이페이지 표시용) */
export const PASSWORD_CHANGED_AT = '2026-02-08'
