import type { ActivitySummary, DashboardKpi, TodoItem } from './types'

/** 백엔드 연동 전 화면 확인용 본사 전체 집계 KPI (국내 ~12,000 SKU 규모 기준) */
export const DASHBOARD_KPI_FIXTURE: DashboardKpi = {
  activePoAmount: 482310000,
  activePoCount: 27,
  adjustDelta: 18,
  arrivingPoCount: 14,
  avgApprovalWaitHours: 18,
  delayedPoCount: 3,
  lowStockCount: 317,
  noStockCount: 48,
  pendingApprovalCount: 9,
  pendingShipCount: 22,
  recentAdjustCount: 142,
  totalSkuCount: 12438,
}

/** 할 일 목록 — 본사 전체 지점 집계(승인 대기 9 / 출고 대기 8 / 도착 지연 6 = 총 23건) */
export const TODO_FIXTURES: TodoItem[] = [
  {
    category: 'APPROVAL',
    id: 1,
    itemSummary: '엔진오일 필터 외 4건',
    reqNo: 'REQ-2026-0512',
    totalQuantity: 240,
    urgency: 'DELAYED',
    warehouseName: '부산 2창고',
    whenLabel: 'D+1',
  },
  {
    category: 'APPROVAL',
    id: 2,
    itemSummary: '배터리 12V 80Ah',
    reqNo: 'REQ-2026-0511',
    totalQuantity: 40,
    urgency: 'DELAYED',
    warehouseName: '인천 1창고',
    whenLabel: 'D+1',
  },
  {
    category: 'APPROVAL',
    id: 3,
    itemSummary: '브레이크 패드 세트 외 2건',
    reqNo: 'REQ-2026-0510',
    totalQuantity: 120,
    urgency: 'TODAY',
    warehouseName: '대구 1창고',
    whenLabel: '오늘 12:08',
  },
  {
    category: 'APPROVAL',
    id: 4,
    itemSummary: '쇼크업소버 (후륜, RH)',
    reqNo: 'REQ-2026-0509',
    totalQuantity: 60,
    urgency: 'TODAY',
    warehouseName: '대구 1창고',
    whenLabel: '오늘 09:51',
  },
  {
    category: 'APPROVAL',
    id: 5,
    itemSummary: '헤드램프 어셈블리 LH',
    reqNo: 'REQ-2026-0508',
    totalQuantity: 24,
    urgency: 'NORMAL',
    warehouseName: '광주 1창고',
    whenLabel: '어제 17:30',
  },
  {
    category: 'APPROVAL',
    id: 6,
    itemSummary: '스파크 플러그 (이리듐) 외 1건',
    reqNo: 'REQ-2026-0506',
    totalQuantity: 480,
    urgency: 'NORMAL',
    warehouseName: '대전 1창고',
    whenLabel: '어제 14:02',
  },
  {
    category: 'APPROVAL',
    id: 7,
    itemSummary: '도어 미러 (전동 접이식)',
    reqNo: 'REQ-2026-0505',
    totalQuantity: 30,
    urgency: 'NORMAL',
    warehouseName: '서울 1창고',
    whenLabel: '05-19 10:14',
  },
  {
    category: 'APPROVAL',
    id: 8,
    itemSummary: '에어 클리너 카트리지 외 2건',
    reqNo: 'REQ-2026-0504',
    totalQuantity: 96,
    urgency: 'NORMAL',
    warehouseName: '서울 2창고',
    whenLabel: '05-19 09:33',
  },
  {
    category: 'APPROVAL',
    id: 9,
    itemSummary: '워터 펌프 어셈블리',
    reqNo: 'REQ-2026-0503',
    totalQuantity: 18,
    urgency: 'NORMAL',
    warehouseName: '부산 1창고',
    whenLabel: '05-18 16:20',
  },
  {
    category: 'SHIP',
    id: 10,
    itemSummary: '스파크 플러그 (이리듐)',
    reqNo: 'REQ-2026-0509',
    totalQuantity: 160,
    urgency: 'TODAY',
    warehouseName: '대전 1창고',
    whenLabel: '오늘 11:02',
  },
  {
    category: 'SHIP',
    id: 11,
    itemSummary: '헤드램프 어셈블리 LH 외 1건',
    reqNo: 'REQ-2026-0508',
    totalQuantity: 64,
    urgency: 'TODAY',
    warehouseName: '광주 1창고',
    whenLabel: '오늘 10:15',
  },
  {
    category: 'SHIP',
    id: 12,
    itemSummary: '엔진오일 필터 외 5건',
    reqNo: 'REQ-2026-0510',
    totalQuantity: 248,
    urgency: 'NORMAL',
    warehouseName: '강남 1지점',
    whenLabel: '어제 16:40',
  },
  {
    category: 'SHIP',
    id: 13,
    itemSummary: '브레이크 오일 DOT4 1L',
    reqNo: 'REQ-2026-0501',
    totalQuantity: 25,
    urgency: 'NORMAL',
    warehouseName: '제주 노형지점',
    whenLabel: '어제 13:22',
  },
  {
    category: 'SHIP',
    id: 14,
    itemSummary: '에어 클리너 카트리지',
    reqNo: 'REQ-2026-0500',
    totalQuantity: 48,
    urgency: 'NORMAL',
    warehouseName: '대구 수성지점',
    whenLabel: '05-19 15:08',
  },
  {
    category: 'SHIP',
    id: 15,
    itemSummary: '엔진 쿨런트 1L 외 1건',
    reqNo: 'REQ-2026-0499',
    totalQuantity: 88,
    urgency: 'NORMAL',
    warehouseName: '강남 1지점',
    whenLabel: '05-19 11:40',
  },
  {
    category: 'SHIP',
    id: 16,
    itemSummary: '와이퍼 블레이드 24"',
    reqNo: 'REQ-2026-0497',
    totalQuantity: 30,
    urgency: 'NORMAL',
    warehouseName: '인천 남동지점',
    whenLabel: '05-18 17:55',
  },
  {
    category: 'SHIP',
    id: 17,
    itemSummary: '클러치 디스크',
    reqNo: 'REQ-2026-0496',
    totalQuantity: 12,
    urgency: 'NORMAL',
    warehouseName: '부산 해운대지점',
    whenLabel: '05-18 14:10',
  },
  {
    category: 'ARRIVAL',
    id: 18,
    itemSummary: '브레이크 패드 세트 외 2건',
    reqNo: 'REQ-2026-0498',
    totalQuantity: 250,
    urgency: 'DELAYED',
    warehouseName: '강남 1지점',
    whenLabel: 'D+2',
  },
  {
    category: 'ARRIVAL',
    id: 19,
    itemSummary: '스파크 플러그 (이리듐) 외 1건',
    reqNo: 'REQ-2026-0505',
    totalQuantity: 76,
    urgency: 'DELAYED',
    warehouseName: '대구 수성지점',
    whenLabel: 'D+1',
  },
  {
    category: 'ARRIVAL',
    id: 20,
    itemSummary: '헤드램프 어셈블리 LH',
    reqNo: 'REQ-2026-0490',
    totalQuantity: 40,
    urgency: 'DELAYED',
    warehouseName: '광주 서구지점',
    whenLabel: 'D+1',
  },
  {
    category: 'ARRIVAL',
    id: 21,
    itemSummary: '엔진오일 필터 외 3건',
    reqNo: 'REQ-2026-0486',
    totalQuantity: 180,
    urgency: 'DELAYED',
    warehouseName: '대전 유성지점',
    whenLabel: 'D+1',
  },
  {
    category: 'ARRIVAL',
    id: 22,
    itemSummary: '에어컨 컴프레서 풀리',
    reqNo: 'REQ-2026-0482',
    totalQuantity: 22,
    urgency: 'DELAYED',
    warehouseName: '부산 해운대지점',
    whenLabel: 'D+2',
  },
  {
    category: 'ARRIVAL',
    id: 23,
    itemSummary: '도어 미러 (전동 접이식)',
    reqNo: 'REQ-2026-0478',
    totalQuantity: 16,
    urgency: 'DELAYED',
    warehouseName: '인천 남동지점',
    whenLabel: 'D+3',
  },
]

/** 최근 7일 활동 — 일자별 입고/출고/조정 (합계 입고 612 / 출고 330 / 조정 142 = 1,084건) */
export const ACTIVITY_SUMMARY_FIXTURE: ActivitySummary = {
  daily: [
    { adjust: 18, day: '15', inbound: 70, outbound: 40 },
    { adjust: 22, day: '16', inbound: 82, outbound: 45 },
    { adjust: 24, day: '17', inbound: 95, outbound: 55 },
    { adjust: 12, day: '18', inbound: 78, outbound: 38 },
    { adjust: 28, day: '19', inbound: 110, outbound: 60 },
    { adjust: 22, day: '20', inbound: 92, outbound: 50 },
    { adjust: 16, day: '21', inbound: 85, outbound: 42 },
  ],
  totalAdjust: 142,
  totalInbound: 612,
  totalOutbound: 330,
}
