import type { Item } from './types'

/** 백엔드 연동 전 화면 확인용 하드코딩 부품 마스터 데이터 */
export const ITEM_FIXTURES: Item[] = [
  {
    active: true,
    code: 'HMC-EN-00214',
    createdAt: '2023-04-12',
    defaultSafetyStock: 120,
    description: '2.0L 가솔린 엔진 전용 오일 필터. 호환: 쏘나타 DN8, 투싼 NX4.',
    id: 1,
    majorCategory: '엔진',
    middleCategory: '윤활계통',
    name: '엔진오일 필터 (2.0L gasoline)',
    unit: 'EA',
    updatedAt: '2026-05-28',
  },
  {
    active: true,
    code: 'HMC-BR-01102',
    createdAt: '2023-05-09',
    defaultSafetyStock: 300,
    description: '전륜 브레이크 패드 세트(4매). 호환: 그랜저 GN7, K8.',
    id: 2,
    majorCategory: '제동',
    middleCategory: '패드/슈',
    name: '브레이크 패드 세트 (전륜)',
    unit: 'SET',
    updatedAt: '2026-06-02',
  },
  {
    active: true,
    code: 'HMC-EL-04481',
    createdAt: '2024-01-22',
    defaultSafetyStock: 40,
    description: 'AGM 12V 80Ah. ISG 차량 전용.',
    id: 3,
    majorCategory: '전장',
    middleCategory: '전원',
    name: '배터리 12V 80Ah',
    unit: 'EA',
    updatedAt: '2026-04-15',
  },
  {
    active: true,
    code: 'HMC-SU-00937',
    createdAt: '2023-08-22',
    defaultSafetyStock: 60,
    description: null,
    id: 4,
    majorCategory: '현가',
    middleCategory: '댐퍼',
    name: '쇼크업소버 (후륜, RH)',
    unit: 'EA',
    updatedAt: '2026-03-30',
  },
  {
    active: true,
    code: 'HMC-IN-02216',
    createdAt: '2024-05-30',
    defaultSafetyStock: 50,
    description: null,
    id: 5,
    majorCategory: '엔진',
    middleCategory: '흡배기',
    name: '인테이크 매니폴드 가스켓',
    unit: 'EA',
    updatedAt: '2026-05-11',
  },
  {
    active: true,
    code: 'HMC-LT-00088',
    createdAt: '2022-03-14',
    defaultSafetyStock: 80,
    description: 'LED 헤드램프 어셈블리 좌측.',
    id: 6,
    majorCategory: '전장',
    middleCategory: '등화',
    name: '헤드램프 어셈블리 LH',
    unit: 'EA',
    updatedAt: '2026-01-08',
  },
  {
    active: true,
    code: 'HMC-AC-03340',
    createdAt: '2023-12-01',
    defaultSafetyStock: 90,
    description: null,
    id: 7,
    majorCategory: '공조',
    middleCategory: '컴프레서',
    name: '에어컨 컴프레서 풀리',
    unit: 'EA',
    updatedAt: '2026-02-19',
  },
  {
    active: true,
    code: 'HMC-TR-00501',
    createdAt: '2025-01-19',
    defaultSafetyStock: 25,
    description: '자동변속기 오일 ATF SP-IV, 1L 단위.',
    id: 8,
    majorCategory: '변속',
    middleCategory: '오일/액',
    name: '트랜스미션 오일 ATF SP-IV',
    unit: 'L',
    updatedAt: '2026-05-02',
  },
  {
    active: true,
    code: 'HMC-SP-00673',
    createdAt: '2022-09-05',
    defaultSafetyStock: 600,
    description: '이리듐 스파크 플러그, 4개입 박스.',
    id: 9,
    majorCategory: '엔진',
    middleCategory: '점화',
    name: '스파크 플러그 (이리듐)',
    unit: 'BOX',
    updatedAt: '2026-04-27',
  },
  {
    active: false,
    code: 'HMC-WP-00229',
    createdAt: '2021-06-30',
    defaultSafetyStock: 45,
    description: '구형 모델용 — 신규 발주 중지.',
    id: 10,
    majorCategory: '엔진',
    middleCategory: '냉각',
    name: '워터 펌프 어셈블리 (구형)',
    unit: 'EA',
    updatedAt: '2025-11-20',
  },
  {
    active: true,
    code: 'HMC-CL-01769',
    createdAt: '2023-02-11',
    defaultSafetyStock: 30,
    description: null,
    id: 11,
    majorCategory: '구동',
    middleCategory: '클러치',
    name: '클러치 디스크 (수동변속기)',
    unit: 'EA',
    updatedAt: '2026-03-06',
  },
  {
    active: true,
    code: 'HMC-DR-02055',
    createdAt: '2024-08-01',
    defaultSafetyStock: 70,
    description: '전동 접이식 도어 미러 좌측, 열선 포함.',
    id: 12,
    majorCategory: '외장',
    middleCategory: '미러',
    name: '도어 미러 (전동 접이식, LH)',
    unit: 'EA',
    updatedAt: '2026-05-21',
  },
]
